### ISSUE TITLE
Docker Image publish to Github Container Registry?

### ISSUE THREAD

**Issue by AnalogJ** [veertech/localstack-aws-ses-email-viewer#30]
Hey,
Have you considered publishing your docker image to GCR or Docker Hub?

**Comment by veelenga** [comment]
Not yet and we don't have plans to do it right now. One of the possible ways is to pull from GH directly: 

```yml
# docker-compose.yml
# ...
localstack-aws-ses-email-viewer:
  build:
    context: https://github.com/veertech/localstack-aws-ses-email-viewer.git#main
  environment:
    - EXTRA_COLUMNS=Logo=main.png,Domain=domain-small.png
  ports:
    - 3005:3005
```
